### ISSUE TITLE
Task

### ISSUE THREAD

**Issue by JohnKhandygo** [Alexandro9911/Spliter#1]
**Общая формулировка**
Разработать консольную утилиту, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**split**
Разбивает большой текстовый файл на маленькие файлы фиксированного размера. 

file задаёт имя входного файла.
- Флаг -o ofile  задаёт базовое имя выходного файла. Если параметр отсутствует,  базовое имя выходного файла равняется “x”. Если параметр равен “-”, в качестве базового имени выходного файла следует использовать имя входного файла.
- Флаг -d означает, что выходные файлы следует называть “ofile1, ofile2, ofile3, ofile4 …”, где ofile это базовое имя выходного файла. Если же этот параметр не указан, то файлы должны называться “ofileaa, ofileab, ofileac, ofilead … ofileaz ofileba ofilebb …  ”.
- Флаг -l num указывает размер выходных файлов в строчках. По умолчанию выходные файлы имеют размер в 100 строчек.
- Флаг -с num указывает размер выходных файлах в символах.
- Флаг -n num указывает количество выходных файлов. Размер файлов при этом должен считаться автоматически.

Command line: split [-d] [-l num|-c num|-n num] [-o ofile] file

В случае, когда какое-нибудь из имён файлов указано неверно или одновременно указано несколько флагов управления размером, следует выдать ошибку. 

Кроме самой программы, следует написать автоматические тесты к ней.

Рекомендуется следующий подход к разработке:
1. Реализовать класс со всей необходимой логикой так, как Вы это делали в предыдущем задании (с покрытием тестами и прочим). Другими словами, забудьте на время, что Ваше приложение должно работать из консоли.
2. Отдельно написать "обертку", которая будет парсить аргументы командной строки (используя библиотеку) и вызывать разработанные на первом этапе методы. Скорее всего то, что будет написано на втором шаге, даже не потребуется покрывать тестами, поскольку функциональность сторонних библотек обычно не тестируется (либо тестируется в каких-то очень сложных случаях). 

Собственно после готовности первого этапа можно начинать проверку.

**UPD** Также необходимо разработать инструкцию и/или скрипты сборки приложения и его запуска из командной строки (для проверки в реальных условиях).

**Comment by JohnKhandygo** [comment]
По поводу проблемы с тестами. Вы как-то подключали junit к предыдущему проекту. Здесь надо точно также сделать. 

Альтернативный вариант --- использовать какую-нибудь систему сборки, которая умеет управлять проктными зависимостями (то есть сторонними библиотеками, которые Вы хотите использовать в своем проекте). Например, можно использовать [maven](http://maven.apache.org/guides/getting-started/maven-in-five-minutes.html). В этом туториале уже пример с подключенным junit, кстати. Только используйте более новую версию. Версии можно смотреть [здесь](https://mvnrepository.com/). Например, все доступные версии библиотеки junit можно посмотреть [здесь](https://mvnrepository.com/artifact/junit/junit). Вверху списка расположены самые свежие версии, при щелчке по конкретной версии загружается страница, в которой можно скопировать описание зависимости и вставить в pom.xml (основной конфигурационный файл maven, который располагается в корне проекта, на том же уровне, что и папка src). Помимо maven существует еще [gradle](https://gradle.org/guides/). Он более гибкий, но (по крайней мере раньше был) более "геморойный". В современной мире все пользуются одной из этих систем сборок. 

Код еще очень сырой, проверять там особо нечего сейчас, потому что не понятно, к чему Вы придете в процессе разработки. Единственное, что я могу сказать прямо сейчас: в методе `parseByLine` Вы читаете файл дважды (первый раз для того, чтобы количество строк посчитать). Это, конечно, неэффективно, так делать нельзя. Для того, чтобы просто считать файл построчно можно (Вам подходит этот вариант, когда не указан флаг `-n`) лучше использовать любой из подходов, описанных [здесь](https://www.programcreek.com/2011/03/java-read-a-file-line-by-line-code-example/). В случае же, когда необходимо определить размер выходных файлов автоматически (флаг `-n`), видимо, придется оперировать байтами. То есть сначала определить размер файла в байтах, а потом уже его читать посимвольно/побайтово.

**Comment by Alexandro9911** [comment]
что-то я сделал не так, теперь у меня не пушится изменения, и структура полетела... можно я заново все создам в другом репо, а этот удалю?  например вот так, тут и все работает, и структура адекватная https://github.com/Alexandro9911/Split

**Comment by JohnKhandygo** [comment]
Переносите конечно. Только не удаляйте этот пока, я хочу перенести все комментарии, чтобы заново не писать.

**Comment by JohnKhandygo** [comment]
Можете удалять этот репозиторий, если хотите.
